(eval-when-compile
  (require 'cl-lib))

(require 'ert)
(require 'paip-search)

(ert-deftest test-paip-search ()
  (should (equal (paip-search-breadth-first-search 1 (paip-search-is 12) 'paip-search-binary-tree)
	  12))
  (should (equal (paip-search-depth-first-search 1 (paip-search-is 12) (paip-search-finite-binary-tree 15))
	  12))
  (should (equal (paip-search-best-first-search 1 (paip-search-is 12) 'paip-search-binary-tree (paip-search-diff 12))
	  12))
  (should (equal (paip-search-best-first-search 1 (paip-search-is 12) 'paip-search-binary-tree (paip-search-price-is-right 12))
	  12))
  (should (equal (paip-search-beam-search 1 (paip-search-is 12) 'paip-search-binary-tree (paip-search-price-is-right 12) 2)
	  12))
  (should (equal (paip-search-path-state
		  (paip-search-trip (paip-search-city 'San-Francisco)
				    (paip-search-city 'Boston)))
	  '(Boston 71.05 42.21)))
  (should (equal (paip-search-path-state (trip (city 'boston) (city 'san-francisco)))
	  '(SAN-FRANCISCO 122.26 37.47)))
  (should (equal (paip-search-neighbors (paip-search-city 'San-Francisco))
	  '((Los-Angeles 118.15 34.03) (Eugene 123.05 44.03) (Reno 119.49 39.3))))
  (should (equal (paip-search-city 'San-Francisco)
	  '(San-Francisco 122.26 37.47)))
  (should (equal (paip-search-city 'Boston)
	  '(Boston 71.05 42.21)))
  (should (paip-search-air-distance (paip-search-city 'San-Francisco)
			     (paip-search-city 'Boston)))
  (should (equal (paip-search-xyz-coords (paip-search-city 'San-Francisco))
	  '(-0.4238698890637016 0.6670539626516081 0.6126771809492436)))
  (should (equal (paip-search-deg->radians 180.0)
	  3.141592653589793))
  )

(provide 'test-paip-search)

